### ISSUE TITLE
ERR_REQUIRE_ESM after updating to v 4.0.0

### ISSUE THREAD

**Issue by ErikMartensson** [sindresorhus/crypto-random-string#36]
Maybe I've missed something obvious, but I keep getting this error trying to compile my TypeScript project after updating `crypto-random-string` to v 4.0.0.

```
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\projectdir\node_modules\crypto-random-string\index.js
require() of ES modules is not supported.
require() of C:\projectdir\node_modules\crypto-random-string\index.js from C:\projectdir\dist\src\leads\services\leads.service.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\projectdir\node_modules\crypto-random-string\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\projectdir\dist\src\leads\services\leads.service.js:9:56)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\projectdir\dist\src\users\users.service.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

As I understand it, `crypto-random-string` needs a small update before it'll work for me again, but if there's something I should do, please let me know.

**Comment by sindresorhus** [comment]
Please read the release notes.

**Comment by jarretmoses** [comment]
@sindresorhus I am / always have been importing with ESM however I now get this error as well with 4.0

**Comment by nilrae** [comment]
> Please read the release notes.

Solution [https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c](url)
